### ISSUE TITLE
Support  auto-enrollment and configuration file for ziti-edge-tunnel

### ISSUE THREAD

**Issue by sabedevops** [openziti/ziti-tunnel-sdk-c#269]
It would be useful to be able to automatically enroll identities. This would reduce friction when deploying ziti-edge-tunnel via configuration management. For example, a new flag **-I**  to match the `run` command's:

`ziti-edge-tunnel enroll -I /path/to/identities`

The statement above could be used in the `ExecStartPre` section of the systemd service file if made idempotent.

Additionally, it would simply service unit startup procedure if ziti-edge-tunnel supported a configuration file:

```yaml
IdentityFile: /path/to/id.json
IdentitiesDir: /path/to/identities
AutoEnrollTokens: true
UseMultipleIdentities: true  
``` 

By default, ziti-edge-tunnel could read `/opt/ziti/etc/ziti-edge-tunnel.yaml`
or from a new cli flag (**-c**) that accepts a path.
